branches:
  [
    "+([0-9])?(.{+([0-9]),x}).x",
    "master",
    "next",
    "next-major",
    { name: "beta", prerelease: true },
    { name: "alpha", prerelease: true },
  ]
repositoryUrl: https://github.com/front-end-open/wt_run.git
ci: false
dryRun: false
debug: false
extends: "semantic-release-npm-github-publish"
