# 工作流（workflow）名称
# name: Learn-Github-Action
# on: [push] # 工作流触发事件, 目前是push
# jobs:  #  管理此次工作流的所有作业
# check-bats-version:  # 定义作业名称， 检测 bats 版本
# runs-on: ubuntu-latest # 配置作业在 Ubuntu Linux 运行器上运行
#   steps: # 将 check-bats-version 作业中运行的所有步骤组合在一起。 此部分下嵌套的每项都是一个单独的操作或 shell 命令。
#     - uses: actions/checkout@v2 # uses关键字检索或者安装此次步骤所需的action, 这里是告诉运行器，下载actions/checkout@v2. 用于拉取仓库代码并用于特定工具。
#     - uses: actions/setup-node@v2  # 下载node, 以使用npm
#      - run: npm install -g bats  # run关键字告诉作业在运行程序上执行命令
#      - run: bats -v  # 运行 bat

name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps: # 自定义作业中的多个步骤所
      - name: check-out-code
        uses: actions/checkout@v2
      - name: out-info
        uses: actions/setup-node@v1
      - name: Install dep
        run: npm install -g bats
      - name: out-bat-info
        run: bats -v
      - name: out-author-info
        run: |
          echo "this repo author is $OUT_AUTHOR, and email is $OUT_EMAIL"
        env: # 指定步骤需要的环境变量
          OUT_AUTHOR: PachVerb
          OUT_EMAIL: 1506262681@qq.com
