name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - uses: bahmutov/npm-install@v1 # 使用
      - run: npm ci
      - run: npx semantic-release
      - run: npm run version
