name: Build-Artifact
on: [push]
jobs:
  Upload-artifact:
    runs-on: ubuntu-latest
    stes:
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload output files
        uses: actions/upload-artifact@v2
        with: # actions内所需要的参数
          name: output-log-files
          path: output.log
